apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
        - name: tcp-server
          image: allenlin316/tcp-server:v1
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server-service
spec:
  selector:
    app: tcp-server
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
